Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder ".", "/vagrant", disabled: true, SharedFoldersEnableSymlinksCreate: false
    config.vm.provider "virtualbox" do |v|
        v.name = "Vagrant-SCIONdev"
        v.linked_clone = true
        v.memory = 8192
        v.cpus = 4
        v.customize ["modifyvm", :id, "--audio", "none"]
    end
    config.vm.provision "shell", inline: "apt-get update && apt-get upgrade -y", privileged: true, reboot: true
    config.vm.provision "file", source: "install_docker.sh", destination: "$HOME/install_docker.sh"
    config.vm.provision "file", source: "setup.sh", destination: "$HOME/setup.sh"
    config.vm.provision "shell", inline: "/bin/bash -x $HOME/install_docker.sh", privileged: false, reboot: true
    config.vm.provision "shell", inline: "/bin/bash -x $HOME/setup.sh", privileged: false
end
